export IOTCORE_PROJECT="atkiotcore"
export CHANNEL_NAME="iot-demo"
export IOTCORE_REGISTRY="iot_device_raspberry_pi_sensors"
export IOTCORE_DEVICE="claes_test_device"
export IOTCORE_REGION="europe-west1"
